name: Run Node.js script on a schedule

on:
  push:
  schedule:
    - cron: "0 12 * * *"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: '12.x'
      - run: npm install
      - name: Run script
        run: npm start
        env:
          EMAIL_PASS : ${{ secrets.EMAIL_PASS  }}
          EMAIL_ADDRESS : ${{ secrets.EMAIL_ADDRESS }}
          MONGODB_URI : ${{ secrets.MONGODB_URI }}